//list_product
export const PRODUCT_FETCH_START = "PRODUCT_FETCH_START";
export const PRODUCT_FETCH_SUCCESS = "PRODUCT_FETCH_SUCCESS";
export const PRODUCT_FETCH_FAIL = "PRODUCT_FETCH_FAIL";
//popular product
export const POPULAR_PRODUCT_SUCCESS = "POPULAR_PRODUCT_SUCCESS";
//discount product
export const DISCOUNT_PRODUCT_SUCCESS = "DISCOUNT_PRODUCT_SUCCESS";
//latest product
export const LATEST_PRODUCT_SUCCESS = "LATEST_PRODUCT_SUCCESS";

//category
export const CATEGORY_FETCH_START = "CATEGORY_FETCH_START";
export const CATEGORY_FETCH_SUCCESS = "CATEGORY_FETCH_SUCCESS";
export const CATEGORY_FETCH_FAIL = "CATEGORY_FETCH_FAIL";

// Add to Card
export const CART_START = "CART_START";
export const ADD_TO_CART = "ADD_TO_CART";
export const DECREASE_QUANTITY = "DECREASE_QUANTITY";
export const DELETE_FROM_CART = "ADD_TO_CART";
export const CART_DATA_FETCH = "CARTZ_DATA_FETCH";
export const CART_FAIL = "CART_FAIL";
export const CART_EMPTY = "CART_EMPTY";

// profile

export const LOGIN_START = "LOGIN_START";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const SIGNUP_START = "SIGNUP_START";
export const LOGOUT = "LOGOUT";
